image: mcr.microsoft.com/dotnet/sdk:7.0

stages:
    - build_core
    - publish_core
    - build
    - test
    - publish_remaining

before_script:
    - dotnet nuget add source "$CI_SERVER_URL/api/v4/projects/$CI_PROJECT_ID/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget list source

build_core:
  stage: build_core
  tags:
    - docker
  script:
    - dotnet restore CozyBus/CozyBus.Core/CozyBus.Core.csproj --locked-mode
    - dotnet build CozyBus/CozyBus.Core/CozyBus.Core.csproj -c Release --no-restore --no-dependencies

publish_core:
  stage: publish_core
  tags:
    - docker
  script:
    - dotnet restore CozyBus/CozyBus.Core/CozyBus.Core.csproj --locked-mode
    - dotnet build CozyBus/CozyBus.Core/CozyBus.Core.csproj -c Release --no-restore --no-dependencies
    - dotnet pack CozyBus/CozyBus.Core/CozyBus.Core.csproj -c Release --no-build
    - dotnet nuget push "CozyBus/CozyBus.Core/bin/Release/CozyBus.Core*.nupkg" --source gitlab --skip-duplicate
    - dotnet nuget push "CozyBus/CozyBus.Core/bin/Release/CozyBus.Core*.nupkg" --source nuget.org --skip-duplicate
   
build:
  stage: build
  tags:
    - docker
  script:
    - dotnet restore CozyBus/CozyBus.sln --locked-mode
    - dotnet build CozyBus/CozyBus.sln -c Release --no-restore --no-dependencies

test:
  stage: test
  tags:
    - docker
  script:
    - dotnet restore CozyBus/CozyBus.sln --locked-mode
    - dotnet build CozyBus/CozyBus.sln -c Release --no-restore --no-dependencies
    - dotnet test CozyBus/CozyBus.Tests/CozyBus.Tests.csproj --no-restore

publish_remaining:
  stage: publish
  tags:
    - docker
  script:
    - dotnet restore CozyBus/CozyBus.sln --locked-mode
    - dotnet build CozyBus/CozyBus.sln -c Release --no-restore --no-dependencies
    - dotnet pack CozyBus/CozyBus.sln -c Release --no-build
    - dotnet nuget push "CozyBus/CozyBus.InMemory/bin/Release/CozyBus.InMemory*.nupkg" --source gitlab --skip-duplicate
    - dotnet nuget push "CozyBus/CozyBus.RabbitMQ/bin/Release/CozyBus.RabbitMQ*.nupkg" --source gitlab --skip-duplicate
    - dotnet nuget push "CozyBus/CozyBus.Kafka/bin/Release/CozyBus.Kafka*.nupkg" --source gitlab --skip-duplicate
    - echo "Pushing to nuget.org"
    - dotnet nuget push "CozyBus/CozyBus.InMemory/bin/Release/CozyBus.InMemory*.nupkg" --source nuget.org --skip-duplicate --api-key $NUGET_API_KEY
    - dotnet nuget push "CozyBus/CozyBus.RabbitMQ/bin/Release/CozyBus.RabbitMQ*.nupkg" --source nuget.org --skip-duplicate --api-key $NUGET_API_KEY
    - dotnet nuget push "CozyBus/CozyBus.Kafka/bin/Release/CozyBus.Kafka*.nupkg" --source nuget.org --skip-duplicate --api-key $NUGET_API_KEY
  only:
    - main
