name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Build
      run: dotnet build CozyBus/CozyBus.sln -c Release
      
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/a-legotin/index.json
        env:
            NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Pack
        run: dotnet pack CozyBus/CozyBus.sln -c Release
      - name: Push generated package to GitHub registry
        run: dotnet nuget push CozyBus/CozyBus.Core/bin/Release/*.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
